### ISSUE TITLE
Include use-cases for all operators

### ISSUE THREAD

**Issue by onebree** [anildigital/ruby-operators#11]
For example, how do you use: `~>`, `*args`, `<%=`, etc?

**Comment by anildigital** [comment]
@onebree will add it soon

**Comment by anildigital** [comment]
@onebree you are welcome to add examples / use cases.

**Comment by onebree** [comment]
@anildigital Thank you. I may if I find the time to do so. I do not use some of the above operators often enough to think of a good example though.
