### ISSUE TITLE
Flip-flop?

### ISSUE THREAD

**Issue by andrewstucki** [anildigital/ruby-operators#17]
Any love for the [flip-flop](https://blog.newrelic.com/2015/02/24/weird-ruby-part-3-fun-flip-flop-phenom/) operator?

`( == )..( == )`

**Comment by anildigital** [comment]
@andrewstucki Could you send pull request?

**Comment by anildigital** [comment]
@andrewstucki Flip flop example added now in #efa5a8129123d
