### ISSUE TITLE
"Rose" memoization proposal

### ISSUE THREAD

**Issue by jtzero** [anildigital/ruby-operators#18]
Found the following interesting, and thought of this repo.

from: http://thepugautomatic.com/2016/01/rose-memoization/

'...Clearly this needs a name.

I’ve always thought of it as “rose memoization”, because of the `@ ||=` pattern. It looks like an ASCII rose...'

**Comment by anildigital** [comment]
Please send pull request. Thanks!

**Comment by jtzero** [comment]
sure!
