### ISSUE TITLE
Update mobile header for clearer context

### ISSUE THREAD

**Issue by ashishwadekar** [anildigital/ruby-operators#24]
Hi @anildigital,

It would be great if the mobile header would be clearer for clearer context.
After looking at the banner for the first time, I click it 5 times to realise that we need to click the operator to check out the next one.
![ruby operators 2017-11-02 16-19-46](https://user-images.githubusercontent.com/13130213/32322299-0d812fe0-bfea-11e7-9479-0d1a81b6a0e2.png)

Suggested change:
![ruby operators 2017-11-02 16-24-10](https://user-images.githubusercontent.com/13130213/32322392-697ea75a-bfea-11e7-9f4b-1d0a143f4e44.png)

Sending a PR for this one.

Cheers,
 Ashish

**Comment by anildigital** [comment]
Thanks 👍
