### ISSUE TITLE
Error running webpack-dev-server

### ISSUE THREAD

**Issue by krishnan-mani** [anildigital/ruby-operators#5]
I get the following error when i try to run locally
```
ERROR in ./~/css-loader!./app/assets/lib/css/bootstrap.min.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/glyphicons-halflings-regular.svg in /Users/km/dev/ruby/ruby-operators/app/assets/lib/css
 @ ./~/css-loader!./app/assets/lib/css/bootstrap.min.css 6:3700-3752
```

I am using 
```
$ node_modules/webpack-dev-server/bin/webpack-dev-server.js --watch
```

I also noticed that ```.gitignore``` contains a line to ignore all ```*.svg``` files, so perhaps this was missed in a commit.

**Comment by anildigital** [comment]
Thanks @krishnan-mani for finding out the issue. :+1:  😘

I have fixed mentioned issue. I have also updated README for instructions.
Also bundle.js is now generated on the server and added as part of .gitignore as per your feedback.
